//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Do_an_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id_Category { get; set; }
        public string NameCategory { get; set; }
        public string PictureCategory { get; set; }
        public string JoinDate { get; set; }
        public string Note { get; set; }
    }
}
