//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Do_an_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id_comment { get; set; }
        public Nullable<int> Id_Account { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public string binhluan { get; set; }
    }
}
