//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Do_an_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public int Id_notify { get; set; }
        public Nullable<int> Id_Account { get; set; }
        public Nullable<int> Id_productdetails { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> watched { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
