//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Do_an_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public int Id_productdetails { get; set; }
        public Nullable<int> Id_product { get; set; }
        public string Size { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Promotionalprice { get; set; }
        public string Picture_1 { get; set; }
        public string Picture_2 { get; set; }
        public string Picture_3 { get; set; }
    }
}
