//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Do_an_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_product { get; set; }
        public Nullable<int> Id_danhmuc { get; set; }
        public string NameProduct { get; set; }
        public string Content { get; set; }
        public Nullable<int> sales { get; set; }
        public Nullable<int> views { get; set; }
        public string Imagelinks { get; set; }
        public string JoinDate { get; set; }
    }
}
